spring:
  application:
    name: user
  profiles:
    default: eureka-on
    active: eureka-on
  jpa:
    properties:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddlAuto: none
  datasource:
    url: "jdbc:postgresql://localhost:5434/user"
    username: user
    password: 12345678
server:
  port: ${PORT:0}
  servlet:
    contextPath: /ms-users
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: zipkin, health, metrics, prometheus
