spring:
  application:
    name: user
  jpa:
    properties:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddlAuto: "update"
  datasource:
    url: "jdbc:postgresql://localhost:5434/user"
    username: user
    password: 12345678
server:
  port: ${PORT:0}
  servlet:
    contextPath: /ms-users
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
  tracing:
    sampling:
      probability: 1

