services:
  address_db:
    image: postgres:16.3
    container_name: address_db
    restart: always
    profiles:
      - db
      - address
      - all
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "address"
      POSTGRES_USER: "address"
      POSTGRES_PASSWORD: "12345678"
  patient_db:
    image: postgres:16.3
    container_name: patient_db
    restart: always
    profiles:
      - db
      - patient
      - all
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "patient"
      POSTGRES_USER: "patient"
      POSTGRES_PASSWORD: "12345678"
  user_db:
    image: postgres:16.3
    container_name: user_db
    restart: always
    profiles:
      - db
      - user
      - all
    ports:
      - "5434:5432"
    volumes:
      - ./user/src/main/resources:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345678"
  redis_db:
    image: redis:7.2-alpine
    container_name: redis_db
    restart: always
    profiles:
      - redis
      - all
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning # --requirepass 12345678
  eureka:
    image: tli/cr-eureka:0.0.1
    container_name: cr-eureka
    restart: always
    profiles:
      - eureka
      - ms
      - all
    build:
      context: eureka
    ports:
      - "8761:8761"
  gateway:
    image: tli/cr-gateway:0.0.2
    container_name: cr-gateway
    restart: always
    profiles:
      - gateway
      - ms
      - all
    build:
      context: gateway
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka

  address_ms:
    image: tli/cr-ms-address:0.0.2
    container_name: cr-ms-address
    restart: always
    profiles:
      - address
      - ms
      - all
    build:
      context: address
    depends_on:
      - address_db
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://address_db/address
      - SPRING_DATASOURCE_USERNAME=address
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDLAUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
  patient_ms:
    image: tli/cr-ms-patient:0.0.2
    container_name: cr-ms-patient
    restart: always
    profiles:
      - patient
      - ms
      - all
    build:
      context: patient
    depends_on:
      - patient_db
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient_db/patient
      - SPRING_DATASOURCE_USERNAME=patient
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDLAUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
  user_ms:
    image: tli/cr-ms-user:0.0.2
    container_name: cr-ms-user
    restart: always
    profiles:
      - user
      - ms
      - all
    build:
      context: user
    depends_on:
      - user_db
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_db/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDLAUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
  oauth2_ms:
    image: tli/cr-ms-oauth2:0.0.2
    container_name: cr-ms-oauth2
    restart: always
    profiles:
      - oauth2
      - ms
      - all
    build:
      context: oauth2
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka

