apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/eureka"
  EUREKA_CLIENT_REGISTERWITHEUREKA: "False"
  EUREKA_CLIENT_FETCHREGISTRY: "False"
