apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: tli/cr-eureka:0.0.1
        ports:
        - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761 # cualquier puerto
      targetPort: 8761
      nodePort: 30200