apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-db
  labels:
    app: patient-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-db
  template:
    metadata:
      labels:
        app: patient-db
    spec:
      containers:
      - name: patient-db
        image: postgres:15.1
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: patient-db-storage
          mountPath: /var/lib/postgresql
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: patient-db-config
              key: DB_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: patient-db-config
              key: DB_NAME
      volumes:
        - name: patient-db-storage
          persistentVolumeClaim:
            claimName: patient-db-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: patient-db
spec:
  selector:
    app: patient-db
  ports:
    - protocol: TCP
      port: 5432 # cualquier puerto
      targetPort: 5432