apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: tli/cr-gateway:0.0.2
        ports:
        - containerPort: 8080
        env:
          - name: EUREKA_CLIENT_REGISTERWITHEUREKA
            valueFrom:
              configMapKeyRef:
                name: eureka-config
                key: EUREKA_CLIENT_REGISTERWITHEUREKA
          - name: EUREKA_CLIENT_FETCHREGISTRY
            valueFrom:
              configMapKeyRef:
                name: eureka-config
                key: EUREKA_CLIENT_FETCHREGISTRY
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: SPRING_PROFILES_ACTIVE
          - name: APPLICATION_MICROSERVICES_OAUTH2_HOST
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: APPLICATION_MICROSERVICES_OAUTH2_HOST
          - name: APPLICATION_MICROSERVICES_USER_HOST
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: APPLICATION_MICROSERVICES_USER_HOST
          - name: APPLICATION_MICROSERVICES_PATIENT_HOST
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: APPLICATION_MICROSERVICES_PATIENT_HOST
          - name: APPLICATION_MICROSERVICES_ADDRESS_HOST
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: APPLICATION_MICROSERVICES_ADDRESS_HOST

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080 # cualquier puerto
      targetPort: 8080
      nodePort: 30201