spring.application.name=address
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost/address
spring.datasource.username=address
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/ms-addresses
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
server.port=${PORT:0}
