spring:
  application:
    name: address
  jpa:
    properties:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddlAuto: update
  datasource:
    url: "jdbc:postgresql://localhost/address"
    username: address
    password: 12345678

server:
  servlet:
    contextPath: /ms-addresses
  port: ${PORT:0}

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show:
        details: always
  tracing:
    sampling:
      probability: 1.0
