spring:
  application:
    name: gateway
  profiles:
    default: eureka-on
    active: eureka-on
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

server:
  port: 8080

eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: zipkin, health, metrics, prometheus

application:
  microservices:
    oauth2:
      host: "lb://oauth2"
      path: "/ms-oauth2/auth"
    user:
      host: "lb://user"
    patient:
      host: "lb://patient"
    address:
      host: "lb://address"

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
    reactor:
      netty: INFO
