spring.application.name=auth

application.jwt.secret=DSFGGJVJHVliadsfbgljblqerleri
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5434/auth
spring.datasource.username=auth
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
#server.servlet.context-path=/ms-patients
server.port=8083
