apiVersion: apps/v1
kind: Deployment
metadata:
  name: address
  labels:
    app: address
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
      - name: address
        image: tli/cr-ms-address:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: address-config
              key: SERVER_PORT
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: address-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: address-config
              key: SPRING_DATASOURCE_URL
        - name: EUREKA_CLIENT_FETCHREGISTRY
          valueFrom:
            configMapKeyRef:
              name: eureka-config
              key: EUREKA_CLIENT_FETCHREGISTRY
        - name: EUREKA_CLIENT_REGISTERWITHEUREKA
          valueFrom:
            configMapKeyRef:
              name: eureka-config
              key: EUREKA_CLIENT_REGISTERWITHEUREKA
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: address-db-config
              key: DB_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: address
spec:
  selector:
    app: address
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 8080 # Pod's port
