spring:
  application:
    name: oauth2
  profiles:
    active: eureka-on
server:
  port: ${PORT:0}
  servlet:
    contextPath: /ms-oauth2
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show:
        details: always

application:
  jwt:
    secret:
      key: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  microservices:
    user:
      host: "lb://user"
      path: "/ms-users"
